service: stripe-api-stripe
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs18.x
  lambdaHashingVersion: 20201221

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 9090

functions:
  deleteProduct:
    handler: handlers/db/products.Delete
    events:
      - httpApi:
          path: /products
          method: delete
  createProduct:
    handler: handlers/db/products.Create
    events:
      - httpApi:
          path: /products
          method: post
  updateProduct:
    handler: handlers/db/products.Update
    events:
      - httpApi:
          path: /products
          method: put
  updateProductByExp:
    handler: handlers/db/products.UpdateByExpression
    events:
      - httpApi:
          path: /products/updateByExp
          method: put
  getProduct:
    handler: handlers/db/products.Get
    events:
      - httpApi:
          path: /products/{id}
          method: get
  listProduct:
    handler: handlers/db/products.List
    events:
      - httpApi:
          path: /products/list
          method: post

  createStripeCustomer:
    handler: handlers/customer/createStripeCustomer.createStripeCustomer
    events:
      - httpApi:
          path: /stripe/customers
          method: post
  registration:
    handler: /handlers/db/users.registration
    events:
      - httpApi:
          path: /customers/registration
          method: post
  login:
    handler: /handlers/db/users.login
    events:
      - httpApi:
          path: /customers/login
          method: post
  getStripeCustomer:
    handler: /handlers/customer/getStripeCustomer.getStripeCustomer
    events:
      - httpApi:
          path: /stripe/customers/{id}
          method: get
  deleteStripeCustomer:
    handler: /handlers/customer/deleteStripeCustomer.deleteStripeCustomer
    events:
      - httpApi:
          path: /stripe/customers/{id}
          method: delete

  createStripeSubscription:
    handler: /handlers/subscription/createStripeSubscription.createStripeSubscription
    events:
      - httpApi:
          path: /stripe/subscriptions
          method: post
  stopOrRestartStripeSubscription:
    handler: /handlers/subscription/stopOrRestartStripeSubscription.stopOrRestartStripeSubscription
    events:
      - httpApi:
          path: /stripe/subscriptions/{id}/stop-or-restart
          method: put
  upgradeOrDownGradeSubscription:
    handler: /handlers/subscription/upgradeOrDownGradeSubscription.upgradeOrDownGradeSubscription
    events:
      - httpApi:
          path: /stripe/subscriptions/{id}/upgrade-or-downgrade
          method: put
  getStripeSubscription:
    handler: /handlers/subscription/getStripeSubscription.getStripeSubscription
    events:
      - httpApi:
          path: /stripe/subscriptions/{id}
          method: get
  deleteStripeSubscription:
    handler: /handlers/subscription/deleteStripeSubscription.deleteStripeSubscription
    events:
      - httpApi:
          path: /stripe/subscriptions/{id}
          method: delete

  createStripeProduct:
    handler: /handlers/product/createStripeProduct.createStripeProduct
    events:
      - httpApi:
          path: /stripe/products
          method: post
  updateStripeProduct:
    handler: /handlers/product/updateStripeProduct.updateStripeProduct
    events:
      - httpApi:
          path: /stripe/products/{id}
          method: put
  getStripeProduct:
    handler: /handlers/product/getStripeProduct.getStripeProduct
    events:
      - httpApi:
          path: /stripe/products/{id}
          method: get
  listStripeProducts:
    handler: /handlers/product/listStripeProducts.listStripeProducts
    events:
      - httpApi:
          path: /stripe/products
          method: get

  retrieveCustomerPaymentMethod:
    handler: /handlers/payment/retrieveCustomerPaymentMethod.retrieveCustomerPaymentMethod
    events:
      - httpApi:
          path: /stripe/pm/{id}
          method: get
  createStripeCheckout:
    handler: /handlers/payment/createStripeCheckout.createStripeCheckout
    events:
      - httpApi:
          path: /stripe/subscriptions/create
          method: post
  addOrUpdatePaymentMethod:
    handler: /handlers/payment/addOrUpdatePaymentMethod.addOrUpdatePaymentMethod
    events:
      - httpApi:
          path: /stripe/pm/{id}
          method: post
  upcomingInvoices:
    handler: /handlers/payment/upcomingInvoices.upcomingInvoices
    events:
      - httpApi:
          path: /stripe/invoices/upcoming
          method: post

  webhook:
    handler: /handlers/webhook/webhook.webhook
    events:
      - httpApi:
          path: /stripe/webhook/
          method: post
